#!/usr/bin/env bash

# Dart Format

printf "\e[33;1m%s\e[0m\n" 'Running dart format.'

result=$(dart format lib)
result_lines=$(echo "$result" | wc -l)

if [ "$result_lines" -gt 1 ]; then
  echo "$result"
  printf "\e[31;1m%s\e[0m\n" 'Dart format applied changes, please commit again.'
  exit 1
fi

echo "$result"
printf "\e[32;1m%s\e[0m\n" 'Finished running dart format.'

# Get the commit message.

#COMMIT_MSG_FILE=$1
#COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")
COMMIT_MSG=$(git log -1 --pretty=%B)

# Check if the commit message starts with 'Bump version'.

#if [[ $COMMIT_MSG == Bump\ version* ]]; then
if [[ $COMMIT_MSG == Test\ version* ]]; then
    printf "\e[33;1m%s\e[0m\n" 'Update versions.'

    # Run make versions.

    make versions

    # Add any changed files to the commit.

    git add .

    echo $(git status)
    echo "DONE"
fi
