name: geopod
description: "Map interface to Solid Server Data Vault Pods."
publish_to: 'none'
version: 0.0.2+2

environment:
  sdk: ^3.10.0

# 20250722 gjw To automatically upgrade package dependencies:
#
#   flutter pub upgrade --major-versions
#
# To see which dependencies have newer versions available:
#
#   flutter pub outdated

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  http: ^1.2.2
  latlong2: ^0.9.1
  shared_preferences: ^2.3.3
  solidpod: 0.8.5
  solidui: ^0.0.8
  web: ^1.1.0
  window_manager: ^0.5.0
  universal_io: any

dev_dependencies:
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/app_icon.png
    - assets/images/app_image.png
    - assets/data/places.json
  uses-material-design: true

# 20250429 gjw Define launcher icons for all platforms (except Linux)
# so icons for the apps can be automatically updated using:
#
# `dart run flutter_launcher_icons`

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  macos:
    generate: true
  web:
    generate: true
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
